//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "8.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St Luke Serbian Orthodox Church.
        /// </summary>
        internal static string _1_title {
            get {
                return ResourceManager.GetString("1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        internal static string _10_directions_page_title {
            get {
                return ResourceManager.GetString("10_directions_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions:.
        /// </summary>
        internal static string _11_directions_directions {
            get {
                return ResourceManager.GetString("11_directions_directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        internal static string _12_directions {
            get {
                return ResourceManager.GetString("12_directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string _13_whatsnew_updated {
            get {
                return ResourceManager.GetString("13_whatsnew_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        internal static string _14_schedules_page_title {
            get {
                return ResourceManager.GetString("14_schedules_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-Line donations.
        /// </summary>
        internal static string _15_donation_page_title {
            get {
                return ResourceManager.GetString("15_donation_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;p&gt;Unfortunately, we decided to cancel Internet donations. Response was very weak, ~$200 per month on average, and considering that we had to pay monthly for this service no matter how much money donated, we decided to cancel this convenient way for donations.
        ///
        ///      &lt;p&gt;Instead, please, mail us your check to the church address (bellow).
        ///
        ///      &lt;p&gt;Thank you very much!
        ///
        ///
        ///      &lt;p&gt;10660 River Road&lt;br&gt;
        ///      Potomac, Maryland 20854
        ///    .
        /// </summary>
        internal static string _16_donation_instruction {
            get {
                return ResourceManager.GetString("16_donation_instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose amount.
        /// </summary>
        internal static string _17_donation_select_amount {
            get {
                return ResourceManager.GetString("17_donation_select_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You forgot to choose donation..
        /// </summary>
        internal static string _18_donation_missing {
            get {
                return ResourceManager.GetString("18_donation_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid amount..
        /// </summary>
        internal static string _19_donation_notvalid {
            get {
                return ResourceManager.GetString("19_donation_notvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      Troparion, Tone 3:&lt;br&gt;
        ///      Holy Apostle Luke, intercede with&lt;br&gt;
        ///      God all merciful that He may grant us&lt;br&gt;
        ///      remission of sins.
        ///    .
        /// </summary>
        internal static string _2_home_religius {
            get {
                return ResourceManager.GetString("2_home_religius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string _20_donation_submit {
            get {
                return ResourceManager.GetString("20_donation_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min $5.
        /// </summary>
        internal static string _21_donation_min {
            get {
                return ResourceManager.GetString("21_donation_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;table height=&quot;20&quot;&gt;
        ///      &lt;tr&gt;
        ///      &lt;td&gt;
        ///      &lt;span class=&quot;footerChat&quot;&gt;
        ///      &lt;!-- Boldcenter Live Chat Button HTML v1.10 (Type=Web,ChatButton=- None -,ChatWindow=- None -,Website=- None -) --&gt;
        ///      &lt;a href=&quot;http://chat.boldcenter.com/aid/304086841263900764/bc.chat&quot; target=&quot;_blank&quot;
        ///      onClick=&quot;this.newWindow = window.open(&apos;http://chat.boldcenter.com/aid/304086841263900764/bc.chat?url=&apos; + document.location, &apos;Chat&apos;, &apos;toolbar=0,scrollbars=1,location=0,statusbar=0,menubar=0,resizable=1,width [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _22_footer_chat {
            get {
                return ResourceManager.GetString("22_footer_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for Your Donation!.
        /// </summary>
        internal static string _23_thinkyou_title {
            get {
                return ResourceManager.GetString("23_thinkyou_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;/SvLuka/Donations/donation.aspx&quot;&gt;&lt;font size=4&gt;&lt;b&gt;On-Line Donations&lt;/b&gt;&lt;/font&gt;&lt;/a&gt;.
        /// </summary>
        internal static string _24_header_donate {
            get {
                return ResourceManager.GetString("24_header_donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;p&gt;Dear dbujakbname,&lt;/p&gt;
        ///
        ///      &lt;p&gt;Thank you so much for your generous donation of $dbujakamount. We can all together make our dream reality - to finally build the church!&lt;/p&gt;
        ///
        ///      &lt;p&gt;Have a great day, and please come again!&lt;/p&gt;
        ///    .
        /// </summary>
        internal static string _24_thankyou_text {
            get {
                return ResourceManager.GetString("24_thankyou_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry....
        /// </summary>
        internal static string _25_sorrypage_title {
            get {
                return ResourceManager.GetString("25_sorrypage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;br&gt;&lt;br&gt;
        ///      PS&lt;br&gt;
        ///      Since your donation was $250 or over, you will receive latter in mail stating so, as required by the US government.
        ///    .
        /// </summary>
        internal static string _25_thankyou_ps {
            get {
                return ResourceManager.GetString("25_thankyou_ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;p&gt;Thank you for trying to donate money, however, there is a problem with your credit card and the system can&apos;t accept it.&lt;/p&gt;
        ///
        ///      &lt;p&gt;You can try again latter, or contact us by phone, e-mail or live chat at the bottom of every page.&lt;/p&gt;
        ///
        ///      &lt;p&gt;We apologize for the inconvenience.&lt;/p&gt;
        ///    .
        /// </summary>
        internal static string _26_sorry_text {
            get {
                return ResourceManager.GetString("26_sorry_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations.
        /// </summary>
        internal static string _27_donations {
            get {
                return ResourceManager.GetString("27_donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string _28_other {
            get {
                return ResourceManager.GetString("28_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string _29_contactus {
            get {
                return ResourceManager.GetString("29_contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St Luke Church.
        /// </summary>
        internal static string _3_introduction {
            get {
                return ResourceManager.GetString("3_introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos &amp; Videos.
        /// </summary>
        internal static string _30_photos {
            get {
                return ResourceManager.GetString("30_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications.
        /// </summary>
        internal static string _31_newsletter {
            get {
                return ResourceManager.GetString("31_newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday School.
        /// </summary>
        internal static string _32_teenpage {
            get {
                return ResourceManager.GetString("32_teenpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string _33_teenhome {
            get {
                return ResourceManager.GetString("33_teenhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Group.
        /// </summary>
        internal static string _34_teenyouthgroup {
            get {
                return ResourceManager.GetString("34_teenyouthgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teen Page Home.
        /// </summary>
        internal static string _35_teenpage_title {
            get {
                return ResourceManager.GetString("35_teenpage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Sunday School classes begins immediately after Communion of the Divine Liturgy.  &lt;/P&gt;
        ///
        ///
        ///      &lt;p&gt;
        ///      Wayside Elementary School&lt;br&gt;
        ///
        ///10011 Glen Road&lt;br&gt;
        ///Potomac MD 20854&lt;br&gt;&lt;/p&gt;
        ///
        ///
        ///
        ///      &lt;p&gt;We welcome children from pre-school through high school. &lt;/p&gt;
        ///
        ///      &lt;p&gt;For additional information about Sunday School, please contact Becky Kesic at 703-421-1254 or &lt;a href=&quot;mailto:Kesic.becky@verizon.net&quot;&gt;Kesic.becky@verizon.net&lt;/a&gt;.&lt;/p&gt;
        ///
        ///      &lt;br&gt;&lt;br&gt;&lt;br&gt;
        ///
        ///      &lt;p&gt;Dear Teenagers, &lt;/p&gt;
        ///
        ///
        ///
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _36_teenpage_text {
            get {
                return ResourceManager.GetString("36_teenpage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Group.
        /// </summary>
        internal static string _37_youthgroup_title {
            get {
                return ResourceManager.GetString("37_youthgroup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;P style=&quot;MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px; FONT-FAMILY: &apos;Kristen ITC&apos;&quot;
        ///      align=center&gt;&lt;FONT size=5&gt;&lt;STRONG&gt;Teen Youth Group&lt;/STRONG&gt;&lt;/FONT&gt;&lt;/P&gt;
        ///      &lt;P style=&quot;MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px; FONT-FAMILY: &apos;Kristen ITC&apos;&quot;
        ///      align=center&gt; &lt;/P&gt;
        ///      &lt;P style=&quot;MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px; FONT-FAMILY: &apos;Kristen ITC&apos;&quot;
        ///      align=left&gt;ARE YOU . . . . &lt;/P&gt;
        ///      &lt;UL&gt;
        ///      &lt;LI&gt;
        ///      &lt;DIV style=&quot;MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px; FONT-FAMILY: &apos;Kristen ITC&apos;&quot;
        ///      align=l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _38_youthgroup_text {
            get {
                return ResourceManager.GetString("38_youthgroup_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY DO WE FACE EAST WHEN WE PRAY?.
        /// </summary>
        internal static string _39_eastpage_title {
            get {
                return ResourceManager.GetString("39_eastpage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Campaign.
        /// </summary>
        internal static string _4_home {
            get {
                return ResourceManager.GetString("4_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;P class=MsoNormal&gt;&lt;FONT face=&quot;Lucida Sans&quot;&gt;&lt;SPAN style=&quot;FONT-SIZE: 11pt&quot;&gt;Have
        ///      you ever asked yourself why we have to turn toward the &lt;I&gt;east &lt;/I&gt;when we pray,
        ///      or why the altar in our Orthodox churches is placed on the east side, or why we
        ///      put icons on the east wall in our homes, or why do we bury people facing the
        ///      east? These and many other questions concerning our faith arise every day.
        ///      Certainly, they need an explanation.&lt;/SPAN&gt;&lt;/FONT&gt;&lt;/P&gt;
        ///      &lt;P class=p3 sty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _40_eastpage_text {
            get {
                return ResourceManager.GetString("40_eastpage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS TATTOOING OR BODY PIERCING REALLY BAD?!!.
        /// </summary>
        internal static string _41_tattooingpage_title {
            get {
                return ResourceManager.GetString("41_tattooingpage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;P class=MsoNormal style=&quot;MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px&quot;
        ///      align=center&gt;&lt;FONT face=&quot;Lucida Sans&quot;&gt;&lt;B&gt; &lt;/B&gt;&lt;I&gt;“Everything is permissible for
        ///      me&lt;/I&gt;&lt;/FONT&gt;&lt;/P&gt;
        ///      &lt;P class=MsoNormal
        ///      style=&quot;MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px; TEXT-ALIGN: center&quot;
        ///      align=center&gt;&lt;FONT face=&quot;Lucida Sans&quot;&gt;&lt;I&gt;-but not everything is beneficial “(1
        ///      &lt;/I&gt;Cor 6: 2)&lt;/FONT&gt;&lt;/P&gt;
        ///      &lt;P class=MsoNormal&gt;&lt;FONT face=&quot;Lucida Sans&quot;&gt;      Very often in our lives, we
        ///      hear the words that ou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _42_tattooingpage_text {
            get {
                return ResourceManager.GetString("42_tattooingpage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Prayer Ropes .
        /// </summary>
        internal static string _43_ropespage_title {
            get {
                return ResourceManager.GetString("43_ropespage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;P align=justify&gt;&lt;FONT face=&quot;Lucida Sans&quot;&gt;Praying with prayer ropes is one of
        ///      the oldest ways of doing prayers, mostly used by monks. Prayer ropes have a
        ///      symbolic character. Most of them are made in &lt;B&gt;black color&lt;/B&gt;, which reminds
        ///      us to live solemn lives in repentance. They are made of &lt;B&gt;pure wool&lt;/B&gt;, which
        ///      signifies that we are the rational ships of the &lt;U&gt;Good Shepherd-Jesus Christ,
        ///      who as an innocent Lamb of God had suffered and died on the cross for our
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _44_ropespage_text {
            get {
                return ResourceManager.GetString("44_ropespage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string _45_contactus_title {
            get {
                return ResourceManager.GetString("45_contactus_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;center&gt;St. Luke Serbian Orthodox Church&lt;br&gt;
        ///
        ///      10660 River Road &lt;br&gt;
        ///
        ///      Potomac, Maryland  20854&lt;br&gt;
        ///
        ///      Telephone (301) 299-2704  &lt;br&gt;
        ///
        ///      Fax (301) 576-5664&lt;br&gt;&lt;/center&gt;
        ///
        ///      &lt;br&gt;&lt;br&gt;
        ///
        ///      Father Aleksa Micich, Parish Priest&lt;br&gt;
        ///
        ///      email:  &lt;a href=&quot;mailto:FatherMicich@svluka.org&quot;&gt;FatherMicich@svluka.org&lt;/a&gt;&lt;br&gt;
        ///
        ///
        ///      &lt;br&gt;
        ///      Mark Rasevic, Church Board President&lt;br&gt;
        ///
        ///      email:  &lt;a href=&quot;mailto:President@svluka.org&quot;&gt;President@svluka.org&lt;/a&gt;&lt;/br&gt;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _46_contactus_text {
            get {
                return ResourceManager.GetString("46_contactus_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications.
        /// </summary>
        internal static string _47_newsletterpage_title {
            get {
                return ResourceManager.GetString("47_newsletterpage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;P&gt;You will need to
        ///      have Acrobat Reader to read the publications. If you don&apos;t have it, you can
        ///      download it for free by &lt;A href=&quot;http://www.adobe.com/products/acrobat/readstep2.html&quot; target=&quot;_blank&quot;&gt;
        ///      clicking here&lt;/A&gt;.&lt;/P&gt;.
        /// </summary>
        internal static string _48_newsletterpage_text {
            get {
                return ResourceManager.GetString("48_newsletterpage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos and Videos.
        /// </summary>
        internal static string _49_photospage_title {
            get {
                return ResourceManager.GetString("49_photospage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        internal static string _5_whatsnew {
            get {
                return ResourceManager.GetString("5_whatsnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;
        ///    2013&lt;ul&gt;
        ///              &lt;li&gt;&lt;a href=&quot;javascript:void(0)&quot; onclick=&quot;myOpen(&apos;2013/SvSava.htm&apos;)&quot;&gt;St Sava - compilation of pictures and video&lt;/a&gt; &lt;/li&gt;
        ///              &lt;li&gt;&lt;a href=&quot;javascript:void(0)&quot; onclick=&quot;myOpen(&apos;2013/SvSava2.htm&apos;)&quot;&gt;St Sava - event and interviews&lt;/a&gt; &lt;/li&gt;
        ///              &lt;li&gt;&lt;a href=&quot;javascript:void(0)&quot; onclick=&quot;myOpen(&apos;2013/SvSava3.htm&apos;)&quot;&gt;St Sava - Folklore everything&lt;/a&gt; &lt;/li&gt;
        ///	      &lt;li&gt;&lt;a href=&quot;http://www.facebook.com/media/set/?set=a.10200741251400229.2209520.1430433604&amp;type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _50_photospage_text {
            get {
                return ResourceManager.GetString("50_photospage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2002 Photos.
        /// </summary>
        internal static string _51_2002photos_title {
            get {
                return ResourceManager.GetString("51_2002photos_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;TABLE style=&quot;BORDER-COLLAPSE: collapse&quot; borderColor=&quot;#111111&quot; height=&quot;990&quot; cellSpacing=&quot;8&quot;
        ///      cellPadding=&quot;0&quot; border=&quot;0&quot; ID=&quot;Table1&quot;&gt;
        ///      &lt;TBODY&gt;
        ///      &lt;TR&gt;
        ///      &lt;TD height=&quot;94&quot;&gt;
        ///      &lt;P style=&quot;MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px&quot; align=&quot;center&quot;&gt;&lt;B&gt;&lt;FONT face=&quot;Lucida Sans&quot; size=&quot;4&quot;&gt;Photos
        ///      From Events in 2002&lt;/FONT&gt;&lt;/B&gt;&lt;/P&gt;
        ///      &lt;HR style=&quot;BORDER-RIGHT: 1px groove; BORDER-TOP: 1px groove; BORDER-LEFT: 1px groove; BORDER-BOTTOM: 1px groove&quot;
        ///      width=&quot;70%&quot; color=&quot;#000000&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _52_2002photos_text {
            get {
                return ResourceManager.GetString("52_2002photos_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2004 Photos.
        /// </summary>
        internal static string _53_2004photos_title {
            get {
                return ResourceManager.GetString("53_2004photos_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;P style=&quot;MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px&quot; align=center&gt;&lt;FONT
        ///      face=&quot;Lucida Sans&quot;&gt;&lt;TT&gt;&lt;FONT face=&quot;Lucida Sans&quot;&gt;&lt;B&gt;PARISH OF ST. APOSTLE AND
        ///      EVANGELIST LUKE ACQUIRES &lt;/B&gt;&lt;/FONT&gt;&lt;/TT&gt;&lt;/FONT&gt;&lt;/P&gt;
        ///      &lt;P style=&quot;MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px&quot; align=center&gt;&lt;FONT
        ///      face=&quot;Lucida Sans&quot;&gt;&lt;TT&gt;&lt;FONT face=&quot;Lucida Sans&quot;&gt;&lt;B&gt;AND BLESSES NEW ALTAR
        ///      WARES&lt;/B&gt;&lt;/FONT&gt;&lt;/TT&gt;&lt;/FONT&gt;&lt;/P&gt;
        ///      &lt;P style=&quot;MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px&quot; align=justify&gt;&lt;FONT
        ///      face=&quot;Lucida Sans&quot;&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _54_2004photos_text {
            get {
                return ResourceManager.GetString("54_2004photos_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donated so far.
        /// </summary>
        internal static string _55_right_label {
            get {
                return ResourceManager.GetString("55_right_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Log-in.
        /// </summary>
        internal static string _56_admin_log_in {
            get {
                return ResourceManager.GetString("56_admin_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string _57_admin_log_out {
            get {
                return ResourceManager.GetString("57_admin_log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that schedule is subject to change without notice..
        /// </summary>
        internal static string _58_schedule_disclamer {
            get {
                return ResourceManager.GetString("58_schedule_disclamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations.
        /// </summary>
        internal static string _59_donations_page_title {
            get {
                return ResourceManager.GetString("59_donations_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string _6_schedules {
            get {
                return ResourceManager.GetString("6_schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;p&gt;You can help your Church in many ways:&lt;/p&gt;
        ///      &lt;ul&gt;
        ///      &lt;li&gt;&lt;a href=&quot;Prayer.aspx&quot;&gt;By prayer&lt;/a&gt; &lt;/li&gt;
        ///      &lt;li&gt;&lt;a href=&quot;Time.aspx&quot;&gt;By donating your time&lt;/a&gt;&lt;/li&gt;
        ///      &lt;li&gt;&lt;a href=&quot;https://secure.etransfer.com/SLSOC/donate.cfm&quot; target=_blank&gt;By donating your money&lt;/a&gt;&lt;/li&gt;
        ///    .
        /// </summary>
        internal static string _60_donations_text {
            get {
                return ResourceManager.GetString("60_donations_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helping by prayer.
        /// </summary>
        internal static string _61_prayer_page_title {
            get {
                return ResourceManager.GetString("61_prayer_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;p&gt;You can pray for our sick, diseased, poor or members in other needs; for our church to grow bigger; for our spiritual leader to help us understand God’s word and will; for our board to be able to overcome all the obstacles and build church on our property; or of course anything else that you see fit.
        ///      &lt;/p&gt;
        ///    .
        /// </summary>
        internal static string _62_prayer_text {
            get {
                return ResourceManager.GetString("62_prayer_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helping with your time.
        /// </summary>
        internal static string _63_time_page_title {
            get {
                return ResourceManager.GetString("63_time_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;p&gt;As you can imagine, it is not easy to meet day to day church business. While we’re renting a hall for our Liturgies, all the items are transported every time to a hall and back to our property (mostly done by just one person). We mail over 600 letter in our mailings, so one can imagine it takes quite some time to prepare all of those and mail. Church property needs maintenance. Church events always are in need for extra volunteers for organizing and cleaning up. Kolo needs new members, especially [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _64_time_text {
            get {
                return ResourceManager.GetString("64_time_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helping financially.
        /// </summary>
        internal static string _65_money_page_title {
            get {
                return ResourceManager.GetString("65_money_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;p&gt;Our church would not be able to operate without financial donations as well. Our yearly budget is just under $200,000 which enables us to pay the mortgage, utilities and other bills. Any extra goes toward building fund.&lt;/p&gt;
        ///
        ///      &lt;p&gt;We have 4 funds you can donate your money to:
        ///      &lt;ol&gt;
        ///      &lt;li&gt;Mortgage fund – used to meet our current mortgage obligations&lt;/li&gt;
        ///      &lt;li&gt;Building fund – used to pay for building permits, and other construction costs and construction related costs&lt;/li&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _66_money_text {
            get {
                return ResourceManager.GetString("66_money_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Diary.
        /// </summary>
        internal static string _67_construction_diary {
            get {
                return ResourceManager.GetString("67_construction_diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string _68_forms {
            get {
                return ResourceManager.GetString("68_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC Yellow Pages.
        /// </summary>
        internal static string _69_yellow_pages {
            get {
                return ResourceManager.GetString("69_yellow_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string _7_home_page_title {
            get {
                return ResourceManager.GetString("7_home_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms for Download.
        /// </summary>
        internal static string _70_forms_title {
            get {
                return ResourceManager.GetString("70_forms_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      These are the forms available for download:
        ///      &lt;ul&gt;
        ///      &lt;li&gt;&lt;a href=&quot;/SvLuka/Forms/pledgeEn.pdf&quot; target=&quot;_blank&quot;&gt;Pledge Form&lt;/a&gt;&lt;/li&gt;
        ///      &lt;li&gt;&lt;a href=&quot;/SvLuka/Forms/GivingForm_SLSOChurch.pdf&quot; target=&quot;_blank&quot;&gt;Credit Card / Bank Account donation form&lt;/a&gt;&lt;/li&gt;
        ///      &lt;li&gt;&lt;a href=&quot;/SvLuka/Forms/sunday school.pdf&quot; target=&quot;_blank&quot;&gt;Sunday School Form&lt;/a&gt;&lt;/li&gt;
        ///      &lt;/ul&gt;
        ///      &lt;br&gt;&lt;br&gt;
        ///      &lt;br&gt;&lt;br&gt;
        ///      &lt;br&gt;&lt;br&gt;
        ///      &lt;br&gt;&lt;br&gt;
        ///      &lt;br&gt;&lt;br&gt;
        ///      &lt;br&gt;&lt;br&gt;
        ///    .
        /// </summary>
        internal static string _71_forms_page {
            get {
                return ResourceManager.GetString("71_forms_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Diary.
        /// </summary>
        internal static string _72_construction_title {
            get {
                return ResourceManager.GetString("72_construction_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Coming soon....
        /// </summary>
        internal static string _73_construction_page {
            get {
                return ResourceManager.GetString("73_construction_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Pages.
        /// </summary>
        internal static string _74_yellowpages_title {
            get {
                return ResourceManager.GetString("74_yellowpages_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;p&gt;If you&apos;d like to place your business add here please &lt;a href=&quot;mailto:yellowpages@svluka.org&quot;&gt;
        ///      email us&lt;/a&gt;.&lt;/p&gt;
        ///      &lt;TABLE id=&quot;Table1&quot; cellSpacing=&quot;1&quot; cellPadding=&quot;1&quot; width=&quot;90%&quot; border=&quot;0&quot;&gt;
        ///      &lt;TR&gt;
        ///      &lt;TD vAlign=&quot;top&quot;&gt;
        ///      &lt;TABLE id=&quot;Table3&quot; cellSpacing=&quot;1&quot; cellPadding=&quot;1&quot; width=&quot;100%&quot; border=&quot;0&quot;&gt;
        ///      &lt;TR&gt;
        ///      &lt;TD&gt;&lt;STRONG&gt;Car Repair&lt;/STRONG&gt;&lt;/TD&gt;
        ///      &lt;/TR&gt;
        ///      &lt;TR&gt;
        ///      &lt;TD&gt;
        ///      &lt;UL&gt;
        ///      &lt;LI&gt;
        ///      Jovan&lt;/LI&gt;&lt;/UL&gt;
        ///      &lt;/TD&gt;
        ///      &lt;/TR&gt;
        ///      &lt;TR&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _75_yellowpages_page {
            get {
                return ResourceManager.GetString("75_yellowpages_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-to-date.
        /// </summary>
        internal static string _76_uptodate {
            get {
                return ResourceManager.GetString("76_uptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let Us Know....
        /// </summary>
        internal static string _77_letusknow_title {
            get {
                return ResourceManager.GetString("77_letusknow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;p&gt;Dear parishioners,
        ///
        ///      &lt;p&gt;Our main goal for the newsletter is to reflect what is happening in our parish!
        ///
        ///      &lt;p&gt;The best way we can learn about something is by you letting us know.
        ///
        ///      &lt;p&gt;If you, or somebody you know has had:
        ///      &lt;ul&gt;
        ///      &lt;li&gt;a wedding&lt;/li&gt;
        ///      &lt;li&gt;baptism&lt;/li&gt;
        ///      &lt;li&gt;graduation&lt;/li&gt;
        ///      &lt;li&gt;baby&lt;/li&gt;
        ///      &lt;li&gt;anniversary&lt;/li&gt;
        ///      &lt;li&gt;death&lt;/li&gt;
        ///      &lt;li&gt;or anything else&lt;/li&gt;
        ///      &lt;/ul&gt;
        ///
        ///      Please write us to &lt;a href=&quot;mailto:newslette [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _78_letusknow_page {
            get {
                return ResourceManager.GetString("78_letusknow_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string _79_links {
            get {
                return ResourceManager.GetString("79_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;
        ///    The Campaign for St. Luke Serbian Orthodox Church
        ///    &lt;br /&gt;
        ///    &lt;span style=&quot;font-size: 9pt&quot;&gt;“Let every person give according to the purposes of their
        ///        heart…” (II Corinthians 9:7a)&amp;nbsp;&lt;/span&gt;&lt;/h3&gt;
        ///    Dear Friends and Parishioners of St. Luke Serbian Orthodox Church,&lt;br /&gt;
        ///&lt;br /&gt;
        ///    The above words of St. Paul in his letter to the Corinthians are particularly relevant
        ///    in our effort to successfully complete the Campaign for St. Luke Serbian Orthodox
        ///    Church. You may have  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _8_home_text {
            get {
                return ResourceManager.GetString("8_home_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page with Links.
        /// </summary>
        internal static string _80_links_title {
            get {
                return ResourceManager.GetString("80_links_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to have your church link on this page send e-mail to webmaster (get e-mail from contact us page).
        /// </summary>
        internal static string _81_links_page {
            get {
                return ResourceManager.GetString("81_links_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St Luke&apos;s Mailing List.
        /// </summary>
        internal static string _82_mailinglist_title {
            get {
                return ResourceManager.GetString("82_mailinglist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To subscribe to our mailing list simply put your email address and click subscribe. In addition you can provide us with your name and address if you&apos;d like to receive regular mailings from our Church..
        /// </summary>
        internal static string _83_mailinglist_page {
            get {
                return ResourceManager.GetString("83_mailinglist_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail [mandatory]:.
        /// </summary>
        internal static string _84_mailinglist_email {
            get {
                return ResourceManager.GetString("84_mailinglist_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or not valid e-mail.
        /// </summary>
        internal static string _85_mailinglist_email_error {
            get {
                return ResourceManager.GetString("85_mailinglist_email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string _86_mailinglist_Fname {
            get {
                return ResourceManager.GetString("86_mailinglist_Fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string _87_mailinglist_Lname {
            get {
                return ResourceManager.GetString("87_mailinglist_Lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string _88_mailinglist_Address {
            get {
                return ResourceManager.GetString("88_mailinglist_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City, State and ZIP:.
        /// </summary>
        internal static string _89_mailinglist_CityEtc {
            get {
                return ResourceManager.GetString("89_mailinglist_CityEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        internal static string _9_whatsnew_page_title {
            get {
                return ResourceManager.GetString("9_whatsnew_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string _90_mailinglist_Submit {
            get {
                return ResourceManager.GetString("90_mailinglist_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Fast Days are shown on the calendar &lt;FONT style=&quot;BACKGROUND-COLOR: #C4A883&quot; color=&quot;white&quot;&gt;
        ///      &amp;nbsp;&amp;nbsp;&lt;FONT size=&quot;2&quot;&gt;highlighted&lt;/FONT&gt;&amp;nbsp;&amp;nbsp;&lt;/FONT&gt;&lt;/p&gt;
        ///      &lt;!--&lt;p&gt;On fast days the faitful eat no meat, fish, eggs, dairy products, wine
        ///      (including alcholic beverages in general), or oil - this is indicated with &lt;FONT style=&quot;BACKGROUND-COLOR: #888858&quot; color=&quot;white&quot;&gt;
        ///      &amp;nbsp;&amp;nbsp;&lt;FONT size=&quot;2&quot;&gt;Water&lt;/FONT&gt;&amp;nbsp;&amp;nbsp;&lt;/FONT&gt;.
        ///      &lt;/p&gt;
        ///      &lt;p&gt;On days indicated with &lt;FONT st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _91_5_schedules_page_fast {
            get {
                return ResourceManager.GetString("91.5_schedules_page_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;As you probably noticed, we are using google calendars for our church website. All of our calendars are  public, which means you can have them linked to your &lt;b&gt;cell phone&lt;/b&gt;.&lt;p&gt;Please &lt;a href=&quot;http://support.google.com/calendar/bin/topic.py?hl=en&amp;topic=13950&amp;p=syncmobile&quot;  target=&quot;_blank&quot;&gt;click here&lt;/a&gt; to get detailed instructions how to do that.&lt;p&gt;After you read above instructions, you will need information below:&lt;style type=&quot;text/css&quot;&gt;#dejan td, #dejan th { border-bottom:1px dotted black;padding:5px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _91_7_schedules_calendars {
            get {
                return ResourceManager.GetString("91.7_schedules_calendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on an event on the calendar to get more information..
        /// </summary>
        internal static string _91_schedules_page_page {
            get {
                return ResourceManager.GetString("91_schedules_page_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folklore Ensemble.
        /// </summary>
        internal static string _92_folklore {
            get {
                return ResourceManager.GetString("92_folklore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string _93_folklorehome {
            get {
                return ResourceManager.GetString("93_folklorehome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance Group.
        /// </summary>
        internal static string _94_folklorepage_title {
            get {
                return ResourceManager.GetString("94_folklorepage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;p&gt;
        ///      Dear Parishioners (Parents/Guardians and/or Young Adults),
        ///      &lt;p&gt;
        ///      We would like to take this opportunity to introduce you to the newly formed and
        ///      official St. Luke Serbian Orthodox Church Folklore Ensemble. We value your
        ///      trust in us and the opportunity you afford us to help your child/young adult
        ///      learn more about the Serbian culture and traditional folklore dancing.
        ///      &lt;p&gt;
        ///      With the blessing of our Parish Priest and Bishop, coordinating this depar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _95_folklorepage_text {
            get {
                return ResourceManager.GetString("95_folklorepage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folklore Calendar.
        /// </summary>
        internal static string _97_folklore_calendar {
            get {
                return ResourceManager.GetString("97_folklore_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folklore Calendar.
        /// </summary>
        internal static string _98_folklorecalendarpage_title {
            get {
                return ResourceManager.GetString("98_folklorecalendarpage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeded in the page.
        /// </summary>
        internal static string _99_folkorecalendarpage_text {
            get {
                return ResourceManager.GetString("99_folkorecalendarpage_text", resourceCulture);
            }
        }
    }
}
