<div id="dbujakNavContainer">

		<TABLE  cellSpacing="0"
			cellPadding="0" bgColor="#39586D" border="0" width=180 >
			<TR>
				<TD align="center" height="5"></TD>
			</TR>
			<TR>
				<TD align="center" height=60 valign=top><DIV class="regular"><A href="http://www.oasiscd.com"><IMG src="/images/OasisLoggoBlue.jpg" border="0" width=180 height=53 Alt="Oasis CD Manufacturing"></A></DIV>
				</TD>
			</TR>
			<TR>
				<TD align="center" valign=top height=35>
					<DIV class="regular"><A href="mailto:info@oasiscd.com"><FONT face="Arial" color="#ffffff" size="2"><STRONG>info@oasisCD.com</STRONG></FONT></A></DIV>
						<FONT face="Arial" color="#ffffff" size="2"><STRONG>888.296.2747</STRONG></FONT>
					
				</TD>
			</TR>
			<TR>
				<TD height="3"></TD>
			</TR>
			<TR>
				<TD>


<!-- Group of links -->
<ul id="dbujakNavList">
	<li id="dbujakNavLI" style="margin-top: 2px;"><a href="/music">Introduction to Oasis</a></li>
</ul>
<div id="dbujakNavContainer2">
<ul id="dbujakNavList2">
	<li id="dbujakNavLI2"><a href="/music"><img src="/music/images/NavBarThreeDots.gif" border=0> START HERE</a></li>
	<li id="dbujakNavLI2"><a href="/music/INTRO_top_suite.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Free Tools of Promotion<SUP>TM</SUP></a></li>
	<li id="dbujakNavLI2"><a href="/music/INTRO_musicians_guide.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Beginner's Guide</a></li>
	<li id="dbujakNavLI2"><a href="/music/INTRO_oasis_printing.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Creative Packaging</a></li>
	<li id="dbujakNavLI2"><a href="/music/INTRO_finance.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Financial Assistance</a></li>
</ul>
</div>
<!-- links end -->

<!-- Group of links -->
<ul id="dbujakNavList">
	<li id="dbujakNavLI" style="margin-top: 2px;"><a href="/music/FF_price_list.asp">Pricing</a></li>
</ul>
<div id="dbujakNavContainer2">
<ul id="dbujakNavList2">
	<li id="dbujakNavLI2"><a href="/music/FF_price_list.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> PRICING: Start Here</a></li>
	<li id="dbujakNavLI2"><a href="/music/FF_dvd.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> DVD Pricing</a></li>
	<li id="dbujakNavLI2"><a href="/music/shortrunCDR.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Short-Run CDr/DVDr</a></li>
	<li id="dbujakNavLI2"><a href="/sacd/"><img src="/music/images/NavBarThreeDots.gif" border=0> Dual Discs & SACD</a></li>
	<li id="dbujakNavLI2"><a href="/music/INFO_brochure.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Get Entire Catalog!</a></li>
</ul>
</div>
<!-- links end -->

<!-- Group of links -->
<ul id="dbujakNavList">
	<li id="dbujakNavLI" style="margin-top: 2px;"><a href="/music/FF_order_forms.asp">Forms</a></li>
</ul>
<div id="dbujakNavContainer2">
<ul id="dbujakNavList2">
	<li id="dbujakNavLI2"><a href="/music/FF_order_forms.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Order & IPR Forms</a></li>
	<li id="dbujakNavLI2"><a href="/music/FF_templates.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Graphics Templates</a></li>
	<li id="dbujakNavLI2"><a href="/music/INFO_brochure.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Get Entire Catalog!</a></li>
</ul>
</div>
<!-- links end -->

<!-- Group of links -->
<ul id="dbujakNavList">
	<li id="dbujakNavLI" style="margin-top: 2px;"><a href="/music/INFO_news.asp">Additional Information</a></li>
</ul>
<div id="dbujakNavContainer2">
<ul id="dbujakNavList2">
	<li id="dbujakNavLI2"><a href="/music/INFO_news.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Oasis In The Press!</a></li>
	<li id="dbujakNavLI2"><a href="/music/INTRO_music_conf.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Opportunities/Events</a></li>
	<li id="dbujakNavLI2"><a href="/music/INFO_resource_links.asp"><img src="/music/images/NavBarThreeDots.gif" border=0> Resource Links</a></li>
	<li id="dbujakNavLI2"><a href="mailto:URGENT@oasisCD.com" alt="Response in 3 bus hrs"><img src="/music/images/NavBarThreeDots.gif" border=0> Email us (3 hr response)</a></li>
					  
</ul>
</div>
<!-- links end -->

						<DIV class="search"><FORM id="Form1" action="/cgi-bin/searchmusic/search.pl" method="get">
								<INPUT id="Hidden1" type="hidden" value="1" name="p"> <INPUT id="Hidden2" type="hidden" value="en" name="lang">
								<INPUT id="Hidden3" type="hidden" value="any" name="mode"> Search: <INPUT class="footer" id="Text1" style="WIDTH: 80px" type="text" maxLength="20" align="middle"
									size="8" name="q"> <INPUT id="Image1" type="image" height="20" width="31" src="/music/images/go.gif"
									align="middle" border="0" name="Image1"></Form>
						</DIV>
					</DIV>



				</TD>
			</TR>
			<TR>
				<TD align="left" height="2"></TD>
			</TR>
			<TR>
				<TD align="left" height="2">
				<center><font size=2 color=white>
				FOUR  GREAT WAYS TO HELP
KATRINA VICTIMS DIRECTLY:</font>
				<div class=regular>
				<a target=_blank href="https://american.redcross.org/site/Donation?ACTION=SHOW_DONATION_OPTIONS&CAMPAIGN_ID=1161">
				<img vspace=5 src="/images/ER.jpg" border=0></a>
				

				<a target=_blank href="http://www.jazzfoundation.org/new_orleans.php"><FONT face="Arial" color="#ffffff" size="2"><STRONG>
				Jazz Foundation New Orleans Relief Effort</font></strong></a>
				<br>
				
				<A href="http://www.katrinaspianofund.org/" target=_blank>
				<FONT face=Arial color=#ffffff size=2><STRONG>Katrina's Piano Fund</FONT></STRONG></A>
				<br>
            
				<a target=_blank href="https://www.grammys.com/Donations.aspx?comp=MusiCares"><FONT face="Arial" color="#ffffff" size="2"><STRONG>
				Musicares Hurricane Relief Fund</font></strong></a>
				
				<br>
				<a target=_blank href="https://american.redcross.org/site/Donation?ACTION=SHOW_DONATION_OPTIONS&CAMPAIGN_ID=1161"><FONT face="Arial" color="#ffffff" size="2"><STRONG>
				American Red Cross</font></strong></a>
				

				</div>
				</center>
				</TD>
			</TR>
			<TR>
				<TD align="left" height="20"></TD>
			</TR>
		</TABLE>

</div>